import streamlit as st
from PIL import Image
import numpy as np
import requests


#CONSTANT
API_URL = 'http://localhost:8000/predict_image/'

# Code pour téléchargement de l'image à vérifier

st.set_page_config(page_title="D-FAKE")

st.title("D-FAKE")

menu = st.sidebar.selectbox(
    "MENU",
    ["Home","Check a picture"]
)

if menu == "Home":

    st.header("DeepFake Detection Project")

    st.write("""
    Our application detects fake images generated by AI.
    It uses deep learning models trained with TensorFlow.
    """)


elif menu == "Check a picture":

    st.header("Image Detection")

    uploaded_file = st.file_uploader("Upload your image (PNG,GIF,JPEG,BMP)")


    if uploaded_file:

        image = {'file': Image.open(uploaded_file,'rb')}
        response = requests.post(API_URL, files=image)
        if response.status_code == 200 :
            prediction = response.json()
            result = prediction['fake_real']

            st.write (f'Your picture is a {prediction}')

        #image = Image.open(uploaded_file)
        #st.image(image)

        #label, confidence = predict_image(image)

        #st.subheader("Prediction")


        #st.write(f"Confidence: {confidence*100:.2f}%")

        #
        #
        # st.progress(int(confidence*100))
    else :
        st.write ('No file loaded')
